scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']
  - job_name: 'Spring Boot Application input'
#    metrics_path: '/actuator/prometheus'
#    scrape_interval: 2s
    static_configs:
      - targets: ['localhost:9090']
        labels:
          application: 'My Spring Boot Application'

  - job_name: 'quant-application'
    metrics_path: '/trade/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.1.13:8080', '10.3.217.142:8080']
        labels:
          application: 'Quant Application'